FROM python:3.8-slim-buster
RUN mkdir /app
WORKDIR /app
COPY ./src /app
RUN apt-get update \
  && apt-get -y install --no-install-recommends git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "/app/entrypoint.py"]
